import { pgTable, text, timestamp, uuid, doublePrecision, vector, jsonb, integer } from "drizzle-orm/pg-core";

// --- MEMORY SYSTEM ---
// Stores vectorized trade setups for RAG-based analysis
export const tradeMemories = pgTable("trade_memories", {
  id: uuid("id").primaryKey().defaultRandom(),
  timestamp: timestamp("timestamp").defaultNow().notNull(),
  symbol: text("symbol").notNull(),
  setupDescription: text("setup_description").notNull(),
  embedding: vector("embedding", { dimensions: 768 }), // nomic-embed-text produces 768-dim vectors
  outcome: text("outcome").notNull(), // 'success', 'fail', 'neutral'
  reasoning: text("reasoning").notNull(),
  marketContext: jsonb("market_context").notNull(), // OHLCV data, indicators
  confidence: doublePrecision("confidence").notNull(),
});

// --- SYSTEM LOGS & SELF-HEALING ---
// Stores logs for the DevOps agent to analyze
export const systemLogs = pgTable("system_logs", {
  id: uuid("id").primaryKey().defaultRandom(),
  timestamp: timestamp("timestamp").defaultNow().notNull(),
  level: text("level").notNull(), // 'error', 'info', 'warn'
  source: text("source").notNull(), // 'daemon', 'engine', 'ui'
  message: text("message").notNull(),
  stackTrace: text("stack_trace"),
  isHealed: integer("is_healed").default(0), // 0: no, 1: yes
  healingAction: text("healing_action"),
});

// --- ALERT LOGS ---
// Stores trade signals generated by the Hydra Engine
export const alertLogs = pgTable("alert_logs", {
  id: uuid("id").primaryKey().defaultRandom(),
  timestamp: timestamp("timestamp").defaultNow().notNull(),
  symbol: text("symbol").notNull(),
  direction: text("direction").notNull(), // 'LONG', 'SHORT'
  entry: doublePrecision("entry").notNull(),
  sl: doublePrecision("sl").notNull(),
  tp: doublePrecision("tp").notNull(),
  status: text("status").notNull().default("PENDING"),
  agentReasoning: text("agent_reasoning"),
});
